Repository opendatahub-io/distributed-workloads, pull requests merged in 2025-05, with the labels that each got.

#377 task(RHOAIENG-21368): upgrade Ray version in CUDA image
  .tekton/ray-cuda-push.yaml
  images/runtime/ray/cuda/Dockerfile
  images/runtime/ray/cuda/Pipfile
  images/runtime/ray/cuda/Pipfile.lock
  images/runtime/ray/cuda/README.md
Labels: lgtm, approved

#386 add laurafitzgerald to owners and approvers
  OWNERS
Labels: lgtm, approved

#383 Implement custom test tags for ODH KFTO tests
  README.md
  tests/common/environment.go
  tests/common/test_tag.go
  tests/kfto/kfto_kueue_mnist_upgrade_training_test.go
  tests/kfto/kfto_mnist_sdk_test.go
  tests/kfto/kfto_mnist_training_test.go
  tests/kfto/kfto_pytorchjob_failed_test.go
  tests/kfto/kfto_training_test.go
  tests/kfto/kfto_upgrade_sleep_test.go
Labels: lgtm, approved

#387 task(RHOAIENG-21368): update UBI for ROCm
  images/runtime/ray/rocm/Dockerfile
Labels: lgtm

#319 Add VAP tests for PyTorchJobs
  tests/odh/validating_admission_policy_test.go
Labels: lgtm, approved

#389 Mouth /dev/shm into memory
  tests/kfto/kfto_mnist_training_test.go
  tests/kfto/kfto_training_test.go
Labels: lgtm, approved

#390 Added Github actions for snyk scan
  .github/workflows/snyk-dockerfile-scan.yml
Labels: lgtm, approved, run-snyk

#393 Create Makefile command to generate test images for distributed-workloads
  Makefile
  images/tests/Dockerfile
Labels: lgtm, approved

#379 Removing installation of kubeflow-training as it has been updated in …
  examples/kfto-dreambooth/dreambooth.ipynb
  examples/kfto-sft-llm/sft.ipynb
Labels: lgtm, approved

#395 Add possibility to provide test tier using go lang parameter
  README.md
  tests/common/environment.go
Labels: lgtm, approved

#398 Reapply site-packages permissions after installing pytorch-triton-rocm in ROCm dockerfiles
  images/runtime/training/py311-rocm62-torch241/Dockerfile
  images/runtime/training/py311-rocm62-torch251/Dockerfile
Labels: lgtm, approved

#396 Add workflow to build and push test images
  .github/workflows/build-and-push-test-images.yml
  Makefile
Labels: lgtm, approved

#399 Adjust existing kfto e2e tests to use kueue
  tests/kfto/kfto_mnist_sdk_test.go
  tests/kfto/kfto_mnist_training_test.go
  tests/kfto/kfto_pytorchjob_failed_test.go
  tests/kfto/kfto_training_test.go
  tests/kfto/kfto_upgrade_sleep_test.go
  tests/kfto/resources/mnist_kfto.ipynb
Labels: lgtm

#402 Split e2e tests to dedicated PyTorch241 and PyTorch251
  tests/common/support/defaults.go
  tests/common/support/environment.go
  tests/common/support/environment_test.go
  tests/common/support/test.go
  tests/kfto/kfto_kueue_mnist_upgrade_training_test.go
  tests/kfto/kfto_mnist_sdk_test.go
  tests/kfto/kfto_mnist_training_test.go
  tests/kfto/kfto_pytorchjob_failed_test.go
  tests/kfto/kfto_training_test.go
Labels: lgtm, approved

#404 Specify default test images as env variables in Dockerfile
  .github/workflows/build-and-push-test-images.yml
  images/tests/Dockerfile
Labels: lgtm, approved
